### ISSUE TITLE
Not working for fields with _id suffix?

### ISSUE THREAD

**Issue by mkilling** [rubiety/nilify_blanks#27]
We have a model `Team` that contains a `t.string "stripe_customer_id"` field that references a Customer object on https://stripe.com.

We added nilify_blanks like this:

``` ruby
class Team < ActiveRecord::Base
  nilify_blanks
end
```

However nilify_blanks seems to work for all fields EXCEPT `stripe_customer_id`:

``` sql
(0.1ms)  BEGIN
  SQL (0.6ms)  UPDATE "teams" SET "stripe_customer_id" = '', "billing_address_country" = NULL, "updated_at" = '2015-11-18 14:16:43.918496' WHERE "teams"."id" = 182  [["stripe_customer_id", ""], ["billing_address_country", nil], ["updated_at", Wed, 18 Nov 2015 14:16:43 UTC +00:00], ["id", 182]]
(0.4ms)  COMMIT
```

Is there a special handling for fields that end on `_id` ?

**Comment by jibiel** [comment]
Currently you can nilify `_id` fields only by specifying them explicitly:

```ruby
```

rubiety/nilify_blanks#5 espen/nilify_blanks#6c3ffdbbd6

**Comment by jibiel** [comment]
Currently you can nilify the `_id` fields only by specifying them explicitly:

```ruby
class Team < ActiveRecord::Base
  nilify_blanks only: [:stripe_customer_id, :billing_address_country]
end
```

Note that you'll also have to specify all other columns to be nilified explicitly in the case, like `:billing_address_country`.

I know it sucks but this is the way the solution implemented at the moment.
Feel free to submit a PR.

See rubiety/nilify_blanks#5 and @espen's [fork](https://github.com/espen/nilify_blanks/commit/6c3ffdb) for the details.

**Comment by rubiety** [comment]
Yes, the default implementation which attempts to automatically grab columns to use defers to Rails's `content_columns`. Note that excluding `_id` is *not* something done within `nilify_blanks` - this is a "problem" with `content_columns` within Rails, and we're just using that implementation.

http://apidock.com/rails/ActiveRecord/Base/content_columns/class

This isn't a particularly easy problem to solve, since if we sidestep `content_columns`, we're setting ourselves up for potential issues in the future as we try to decide what should and should not be considered a "content column". I took the conservative approach here and am using that to ensure we don't trounce on any core foreign keys or other non-content columns.

I can see @espen's fork simply converts this to use `columns`, which grabs all columns. I'd be potentially open for doing this here, but need some more real-world evidence that this is safe, including in cases where non-surrogate string keys are in use.

Relatedly, precisely because `_id` is such a strong convention for foreign keys in Rails, I deliberately *avoid* using `_id` in my own apps for anything that is *not* a foreign key, including Stripe identifiers.

**Comment by jibiel** [comment]
@rubiety Thanks for the quick response. I didn't mean to criticise the codebase, just wanted to clarify things a bit.

There are some cases aside from 'external' ids when real-life ids turn up in a database schema, like `Pet#microchip_id`. They're rare, but they are.

Your point is good, it's better to stick with the `content_columns`.

How about introducing explicit attributes: `nilify_blanks explicit: :stripe_customer_id` which basically would be union of `nilify_blanks` and `nilify_blanks only: :stripe_customer_id`?

This is probably overkill for the case and may clutter the API, but it also will keep the `content_columns` in place while potentially help to avoid such issues in the future (like `_count` columns).

**Comment by cruznunez** [comment]
To anyone with a similar problem, I had
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  nilify_blanks types: [:string, :text]
end
```
and wanted to keep that behavior for all models but for one model in particular I also want to nilify a column ending in `_id`. I tried
```
class Student < ApplicationRecord
  nilify_blanks only: :slack_id
  nilify_blanks only: [:slack_id], types: []
  nilify_blanks only: [:slack_id], types: nil
end
```
None of these work for adding that one `_id` column to the list of `nilify_blanks_columns`.

I tried
```
class Student < ApplicationRecord
  def self.nilify_blanks_columns
    super << 'slack_id'
  end
end
```
but that wasn't working.

Then I tried
```
class Student < ApplicationRecord
  def self.content_columns
    super << columns.find { |x| x.name == 'slack_id' }
  end
end
```
and it worked. This keeps the behavior written in ApplicationRecord `types: [:string, :text]` and also adds the column `slack_id` to be nilified as well.

Are there any possible side effects from this monkey patch?

**Comment by rubiety** [comment]
Indeed `content_columns`, within the rails codebase, does automatically exclude any column ending in `_id`, whether or not you're treating it as numeric or a foreign key in practice:

```ruby
      # Returns an array of column objects where the primary id, all columns ending in "_id" or "_count",
      # and columns used for single table inheritance have been removed.
      def content_columns
        @content_columns ||= columns.reject do |c|
          c.name == primary_key ||
          c.name == inheritance_column ||
          c.name.end_with?("_id") ||
          c.name.end_with?("_count")
        end
      end
```

It doesn't seem that `content_columns` is used much *within rails*, so you're probably fine overriding in this specific case, but there could be unintended consequences with other gems relying on this method, so I'd say just be careful with it.

We could probably modify `nilify_blanks` to include the column if explicitly mentioned in `:only` (thus using `content_columns` only for when that option is not chosen, otherwise using all columns from which to filter down), which would alleviate the need to override a Rails method like this. Would be happy to accept a pull request for such a change.

**Comment by Throne3d** [comment]
It looks like `columns` is used instead of `content_columns` as of this merge: https://github.com/rubiety/nilify_blanks/commit/44d5359f6110c2e5212d1ec50c2d0bafd30d4df3 (in v1.3.0).

Should this issue be closed?
