### ISSUE TITLE
Seems to ignore column named `text`

### ISSUE THREAD

**Issue by Lavinia** [rubiety/nilify_blanks#31]
We have a model with a column named `text`.

When we do just `nilify_blanks`, this column is not actually nilified.

When we do ` nilify_blanks only: [ :text ]`, it *is* nilified.

Could it be that this specific column name is treated differently?

In other models, with other column names (such as `body_sv`), the nilification works even when we don't declare the specific columns.

This is Rails 4.1.14.2 and nilify_blanks 1.2.1.

/ @lavinia and @henrik

**Comment by rubiety** [comment]
@Lavinia I suspect in your app that `text` column is somehow not exposing itself to rails with a type of `:text`. If you don't supply an `:only` array, `nilify_blanks` deduces the columns it should grab with this statement:

```ruby
self.content_columns.select(&:null).select {|c| options[:types].include?(c.type) }.map(&:name)
```

So assuming your column is `NULL-able`, it sounds like `type` for your column isn't `:text`. To confirm this, can you run the following in your console and report back the result?

```ruby
YourModel.columns.map {|c| [c.name, c.null, c.type, c.sql_type] }
```

**Comment by henrik** [comment]
Wow, thank you so much for the quick response.

Aah, this would be it then: the column isn't nullable.

We wanted our NOT NULL column to nilify blanks, because we want blank values to cause a DB exception rather than to be saved as blank strings. We also have a presence validation on the column.

We did it this way because of a habit to first add DB level constraints and ensuring those work, then adding Rails-level validations. But perhaps in cases like this one, there's little point in us using nilify_blanks. If someone bypasses Rails callbacks, neither nilify_blanks nor validations will run, anyway.

So I can't think of a good case for contributing an option to also nilify non-nullables. But we could PR a clarification to the docs, maybe.

**Comment by henrik** [comment]
Closing this ticket but please see the referenced PR.
