### ISSUE TITLE
Consider changing the default hook to before_validation

### ISSUE THREAD

**Issue by supersam654** [rubiety/nilify_blanks#35]
We ran into a unexpected issue in our Rails application that could have been avoided with a different default value in `nilify_blanks`.

Here's a (very) trimmed down version of one of our models:

```ruby
class Lab < ActiveRecord::Base
  nilify_blanks

  validates_uniqueness_of :title, scope: [:version_string]
end
```

Because `nilify_blanks` hooks into `before_save` by default, the following lines will create two labs:

```
lab1 = Lab.create(title: "My title", version_string: nil)
lab2 = Lab.create(title: "My title", version_string: '')
```

Practically speaking, we saw this when users would clear the version string on a lab from a form in our UI:

1. A lab starts with a version string set (like "1.0")
2. In the UI, someone clears the version string field
3. We attempt to update a lab with a version string of ""
4. Our validation passes because `"" != nil`
5. Then the empty string turns into a `nil`, the lab saves as if nothing went wrong, and we have data problems now

The above can be avoided by using `nilify_blanks before: :validation` instead (which we're using now). With that said, would it make sense to make that the default for `nilify_blanks` going forward or is there a good reason that the current hook is on `before_save`? I realize changing this would probably be a breaking change at this point.

**Comment by rubiety** [comment]
This is pretty interesting. The primary purpose of `nilify_blanks` is to simply to prevent blank values from being *written to the database*, but I can definitely see how that narrow focus can cause issues with other model logic like uniqueness validations, in your case. There is not a particularly great reason why this isn't the default already.

Indeed I'm hesitant to change that behavior by default because it may cause breaking behavior for some people depending on their usage. But out of curiosity, when you say this:

> I realize changing this would probably be a breaking change at this point.

Did you have anything specific in mind? Just trying to get my head around the full consequences of making a change like this. The only main consequence I can think of is for folks using validators with `allow_nil: true`, since this would now potentially be different than `allow_blank`.

**Comment by supersam654** [comment]
I couldn't come up with any obvious breaking issues with this change.

In a pathological edge case, someone could have a custom validator that branches differently based on if the input is `nil` or an empty string. I don't have a good reason why, but it's possible. 

A potentially larger concern is a hook that sets a field to an empty string. By moving the hook before validations, it's possible for a validation to generate an empty string which would get written to the DB. While still unlikely, a before hook that, for example, strips whitespace from an input could absolutely generate an empty string as its output.

**Comment by espen** [comment]
+1 on this change. We were facing similar issues and solved it by adding `:allow_blank => true` to validations. While adding `:before => :validation` is simple to do I think this makes a better default than the current. It also makes sense to do value changes before validation and not change a value that is validated like now.

**Comment by rubiety** [comment]
I have just pushed `v1.4.0` which includes this default change to `:validation`.
